/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    docs: [
        {
            type: 'doc',
            label: 'Documentation',
            id: 'index'
        },
        {
            type: 'category',
            label: 'Storage Docs',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'storage'
                }
            ]
        },
        {
            type: 'category',
            label: '(QB) Remote Control',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'rc_qb'
                }
            ]
        },
        {
            type: 'category',
            label: '(ESX) Remote Control',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'rc_esx'
                }
            ]
        },
    ]
};

module.exports = sidebars;
